INSERT INTO `countries` VALUES (null, 'AF', 'Afghanistan',now(), now());
INSERT INTO `countries` VALUES (null, 'AL', 'Albania',now(), now());
INSERT INTO `countries` VALUES (null, 'DZ', 'Algeria',now(), now());
INSERT INTO `countries` VALUES (null, 'DS', 'American Samoa',now(), now());
INSERT INTO `countries` VALUES (null, 'AD', 'Andorra',now(), now());
INSERT INTO `countries` VALUES (null, 'AO', 'Angola',now(), now());
INSERT INTO `countries` VALUES (null, 'AI', 'Anguilla',now(), now());
INSERT INTO `countries` VALUES (null, 'AQ', 'Antarctica',now(), now());
INSERT INTO `countries` VALUES (null, 'AG', 'Antigua and Barbuda',now(), now());
INSERT INTO `countries` VALUES (null, 'AR', 'Argentina',now(), now());
INSERT INTO `countries` VALUES (null, 'AM', 'Armenia',now(), now());
INSERT INTO `countries` VALUES (null, 'AW', 'Aruba',now(), now());
INSERT INTO `countries` VALUES (null, 'AU', 'Australia',now(), now());
INSERT INTO `countries` VALUES (null, 'AT', 'Austria',now(), now());
INSERT INTO `countries` VALUES (null, 'AZ', 'Azerbaijan',now(), now());
INSERT INTO `countries` VALUES (null, 'BS', 'Bahamas',now(), now());
INSERT INTO `countries` VALUES (null, 'BH', 'Bahrain',now(), now());
INSERT INTO `countries` VALUES (null, 'BD', 'Bangladesh',now(), now());
INSERT INTO `countries` VALUES (null, 'BB', 'Barbados',now(), now());
INSERT INTO `countries` VALUES (null, 'BY', 'Belarus',now(), now());
INSERT INTO `countries` VALUES (null, 'BE', 'Belgium',now(), now());
INSERT INTO `countries` VALUES (null, 'BZ', 'Belize',now(), now());
INSERT INTO `countries` VALUES (null, 'BJ', 'Benin',now(), now());
INSERT INTO `countries` VALUES (null, 'BM', 'Bermuda',now(), now());
INSERT INTO `countries` VALUES (null, 'BT', 'Bhutan',now(), now());
INSERT INTO `countries` VALUES (null, 'BO', 'Bolivia',now(), now());
INSERT INTO `countries` VALUES (null, 'BA', 'Bosnia and Herzegovina',now(), now());
INSERT INTO `countries` VALUES (null, 'BW', 'Botswana',now(), now());
INSERT INTO `countries` VALUES (null, 'BV', 'Bouvet Island',now(), now());
INSERT INTO `countries` VALUES (null, 'BR', 'Brazil',now(), now());
INSERT INTO `countries` VALUES (null, 'IO', 'British Indian Ocean Territory',now(), now());
INSERT INTO `countries` VALUES (null, 'BN', 'Brunei Darussalam',now(), now());
INSERT INTO `countries` VALUES (null, 'BG', 'Bulgaria',now(), now());
INSERT INTO `countries` VALUES (null, 'BF', 'Burkina Faso',now(), now());
INSERT INTO `countries` VALUES (null, 'BI', 'Burundi',now(), now());
INSERT INTO `countries` VALUES (null, 'KH', 'Cambodia',now(), now());
INSERT INTO `countries` VALUES (null, 'CM', 'Cameroon',now(), now());
INSERT INTO `countries` VALUES (null, 'CA', 'Canada',now(), now());
INSERT INTO `countries` VALUES (null, 'CV', 'Cape Verde',now(), now());
INSERT INTO `countries` VALUES (null, 'KY', 'Cayman Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'CF', 'Central African Republic',now(), now());
INSERT INTO `countries` VALUES (null, 'TD', 'Chad',now(), now());
INSERT INTO `countries` VALUES (null, 'CL', 'Chile',now(), now());
INSERT INTO `countries` VALUES (null, 'CN', 'China',now(), now());
INSERT INTO `countries` VALUES (null, 'CX', 'Christmas Island',now(), now());
INSERT INTO `countries` VALUES (null, 'CC', 'Cocos (Keeling) Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'CO', 'Colombia',now(), now());
INSERT INTO `countries` VALUES (null, 'KM', 'Comoros',now(), now());
INSERT INTO `countries` VALUES (null, 'CG', 'Congo',now(), now());
INSERT INTO `countries` VALUES (null, 'CK', 'Cook Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'CR', 'Costa Rica',now(), now());
INSERT INTO `countries` VALUES (null, 'HR', 'Croatia (Hrvatska)',now(), now());
INSERT INTO `countries` VALUES (null, 'CU', 'Cuba',now(), now());
INSERT INTO `countries` VALUES (null, 'CY', 'Cyprus',now(), now());
INSERT INTO `countries` VALUES (null, 'CZ', 'Czech Republic',now(), now());
INSERT INTO `countries` VALUES (null, 'DK', 'Denmark',now(), now());
INSERT INTO `countries` VALUES (null, 'DJ', 'Djibouti',now(), now());
INSERT INTO `countries` VALUES (null, 'DM', 'Dominica',now(), now());
INSERT INTO `countries` VALUES (null, 'DO', 'Dominican Republic',now(), now());
INSERT INTO `countries` VALUES (null, 'TP', 'East Timor',now(), now());
INSERT INTO `countries` VALUES (null, 'EC', 'Ecuador',now(), now());
INSERT INTO `countries` VALUES (null, 'EG', 'Egypt',now(), now());
INSERT INTO `countries` VALUES (null, 'SV', 'El Salvador',now(), now());
INSERT INTO `countries` VALUES (null, 'GQ', 'Equatorial Guinea',now(), now());
INSERT INTO `countries` VALUES (null, 'ER', 'Eritrea',now(), now());
INSERT INTO `countries` VALUES (null, 'EE', 'Estonia',now(), now());
INSERT INTO `countries` VALUES (null, 'ET', 'Ethiopia',now(), now());
INSERT INTO `countries` VALUES (null, 'FK', 'Falkland Islands (Malvinas)',now(), now());
INSERT INTO `countries` VALUES (null, 'FO', 'Faroe Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'FJ', 'Fiji',now(), now());
INSERT INTO `countries` VALUES (null, 'FI', 'Finland',now(), now());
INSERT INTO `countries` VALUES (null, 'FR', 'France',now(), now());
INSERT INTO `countries` VALUES (null, 'FX', 'France, Metropolitan',now(), now());
INSERT INTO `countries` VALUES (null, 'GF', 'French Guiana',now(), now());
INSERT INTO `countries` VALUES (null, 'PF', 'French Polynesia',now(), now());
INSERT INTO `countries` VALUES (null, 'TF', 'French Southern Territories',now(), now());
INSERT INTO `countries` VALUES (null, 'GA', 'Gabon',now(), now());
INSERT INTO `countries` VALUES (null, 'GM', 'Gambia',now(), now());
INSERT INTO `countries` VALUES (null, 'GE', 'Georgia',now(), now());
INSERT INTO `countries` VALUES (null, 'DE', 'Germany',now(), now());
INSERT INTO `countries` VALUES (null, 'GH', 'Ghana',now(), now());
INSERT INTO `countries` VALUES (null, 'GI', 'Gibraltar',now(), now());
INSERT INTO `countries` VALUES (null, 'GK', 'Guernsey',now(), now());
INSERT INTO `countries` VALUES (null, 'GR', 'Greece',now(), now());
INSERT INTO `countries` VALUES (null, 'GL', 'Greenland',now(), now());
INSERT INTO `countries` VALUES (null, 'GD', 'Grenada',now(), now());
INSERT INTO `countries` VALUES (null, 'GP', 'Guadeloupe',now(), now());
INSERT INTO `countries` VALUES (null, 'GU', 'Guam',now(), now());
INSERT INTO `countries` VALUES (null, 'GT', 'Guatemala',now(), now());
INSERT INTO `countries` VALUES (null, 'GN', 'Guinea',now(), now());
INSERT INTO `countries` VALUES (null, 'GW', 'Guinea-Bissau',now(), now());
INSERT INTO `countries` VALUES (null, 'GY', 'Guyana',now(), now());
INSERT INTO `countries` VALUES (null, 'HT', 'Haiti',now(), now());
INSERT INTO `countries` VALUES (null, 'HM', 'Heard and Mc Donald Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'HN', 'Honduras',now(), now());
INSERT INTO `countries` VALUES (null, 'HK', 'Hong Kong',now(), now());
INSERT INTO `countries` VALUES (null, 'HU', 'Hungary',now(), now());
INSERT INTO `countries` VALUES (null, 'IS', 'Iceland',now(), now());
INSERT INTO `countries` VALUES (null, 'IN', 'India',now(), now());
INSERT INTO `countries` VALUES (null, 'IM', 'Isle of Man',now(), now());
INSERT INTO `countries` VALUES (null, 'ID', 'Indonesia',now(), now());
INSERT INTO `countries` VALUES (null, 'IR', 'Iran (Islamic Republic of)',now(), now());
INSERT INTO `countries` VALUES (null, 'IQ', 'Iraq',now(), now());
INSERT INTO `countries` VALUES (null, 'IE', 'Ireland',now(), now());
INSERT INTO `countries` VALUES (null, 'IL', 'Israel',now(), now());
INSERT INTO `countries` VALUES (null, 'IT', 'Italy',now(), now());
INSERT INTO `countries` VALUES (null, 'CI', 'Ivory Coast',now(), now());
INSERT INTO `countries` VALUES (null, 'JE', 'Jersey',now(), now());
INSERT INTO `countries` VALUES (null, 'JM', 'Jamaica',now(), now());
INSERT INTO `countries` VALUES (null, 'JP', 'Japan',now(), now());
INSERT INTO `countries` VALUES (null, 'JO', 'Jordan',now(), now());
INSERT INTO `countries` VALUES (null, 'KZ', 'Kazakhstan',now(), now());
INSERT INTO `countries` VALUES (null, 'KE', 'Kenya',now(), now());
INSERT INTO `countries` VALUES (null, 'KI', 'Kiribati',now(), now());
INSERT INTO `countries` VALUES (null, 'KP', 'Korea, Democratic People''s Republic of',now(), now());
INSERT INTO `countries` VALUES (null, 'KR', 'Korea, Republic of',now(), now());
INSERT INTO `countries` VALUES (null, 'XK', 'Kosovo',now(), now());
INSERT INTO `countries` VALUES (null, 'KW', 'Kuwait',now(), now());
INSERT INTO `countries` VALUES (null, 'KG', 'Kyrgyzstan',now(), now());
INSERT INTO `countries` VALUES (null, 'LA', 'Lao People''s Democratic Republic',now(), now());
INSERT INTO `countries` VALUES (null, 'LV', 'Latvia',now(), now());
INSERT INTO `countries` VALUES (null, 'LB', 'Lebanon',now(), now());
INSERT INTO `countries` VALUES (null, 'LS', 'Lesotho',now(), now());
INSERT INTO `countries` VALUES (null, 'LR', 'Liberia',now(), now());
INSERT INTO `countries` VALUES (null, 'LY', 'Libyan Arab Jamahiriya',now(), now());
INSERT INTO `countries` VALUES (null, 'LI', 'Liechtenstein',now(), now());
INSERT INTO `countries` VALUES (null, 'LT', 'Lithuania',now(), now());
INSERT INTO `countries` VALUES (null, 'LU', 'Luxembourg',now(), now());
INSERT INTO `countries` VALUES (null, 'MO', 'Macau',now(), now());
INSERT INTO `countries` VALUES (null, 'MK', 'Macedonia',now(), now());
INSERT INTO `countries` VALUES (null, 'MG', 'Madagascar',now(), now());
INSERT INTO `countries` VALUES (null, 'MW', 'Malawi',now(), now());
INSERT INTO `countries` VALUES (null, 'MY', 'Malaysia',now(), now());
INSERT INTO `countries` VALUES (null, 'MV', 'Maldives',now(), now());
INSERT INTO `countries` VALUES (null, 'ML', 'Mali',now(), now());
INSERT INTO `countries` VALUES (null, 'MT', 'Malta',now(), now());
INSERT INTO `countries` VALUES (null, 'MH', 'Marshall Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'MQ', 'Martinique',now(), now());
INSERT INTO `countries` VALUES (null, 'MR', 'Mauritania',now(), now());
INSERT INTO `countries` VALUES (null, 'MU', 'Mauritius',now(), now());
INSERT INTO `countries` VALUES (null, 'TY', 'Mayotte',now(), now());
INSERT INTO `countries` VALUES (null, 'MX', 'Mexico',now(), now());
INSERT INTO `countries` VALUES (null, 'FM', 'Micronesia, Federated States of',now(), now());
INSERT INTO `countries` VALUES (null, 'MD', 'Moldova, Republic of',now(), now());
INSERT INTO `countries` VALUES (null, 'MC', 'Monaco',now(), now());
INSERT INTO `countries` VALUES (null, 'MN', 'Mongolia',now(), now());
INSERT INTO `countries` VALUES (null, 'ME', 'Montenegro',now(), now());
INSERT INTO `countries` VALUES (null, 'MS', 'Montserrat',now(), now());
INSERT INTO `countries` VALUES (null, 'MA', 'Morocco',now(), now());
INSERT INTO `countries` VALUES (null, 'MZ', 'Mozambique',now(), now());
INSERT INTO `countries` VALUES (null, 'MM', 'Myanmar',now(), now());
INSERT INTO `countries` VALUES (null, 'NA', 'Namibia',now(), now());
INSERT INTO `countries` VALUES (null, 'NR', 'Nauru',now(), now());
INSERT INTO `countries` VALUES (null, 'NP', 'Nepal',now(), now());
INSERT INTO `countries` VALUES (null, 'NL', 'Netherlands',now(), now());
INSERT INTO `countries` VALUES (null, 'AN', 'Netherlands Antilles',now(), now());
INSERT INTO `countries` VALUES (null, 'NC', 'New Caledonia',now(), now());
INSERT INTO `countries` VALUES (null, 'NZ', 'New Zealand',now(), now());
INSERT INTO `countries` VALUES (null, 'NI', 'Nicaragua',now(), now());
INSERT INTO `countries` VALUES (null, 'NE', 'Niger',now(), now());
INSERT INTO `countries` VALUES (null, 'NG', 'Nigeria',now(), now());
INSERT INTO `countries` VALUES (null, 'NU', 'Niue',now(), now());
INSERT INTO `countries` VALUES (null, 'NF', 'Norfolk Island',now(), now());
INSERT INTO `countries` VALUES (null, 'MP', 'Northern Mariana Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'NO', 'Norway',now(), now());
INSERT INTO `countries` VALUES (null, 'OM', 'Oman',now(), now());
INSERT INTO `countries` VALUES (null, 'PK', 'Pakistan',now(), now());
INSERT INTO `countries` VALUES (null, 'PW', 'Palau',now(), now());
INSERT INTO `countries` VALUES (null, 'PS', 'Palestine',now(), now());
INSERT INTO `countries` VALUES (null, 'PA', 'Panama',now(), now());
INSERT INTO `countries` VALUES (null, 'PG', 'Papua New Guinea',now(), now());
INSERT INTO `countries` VALUES (null, 'PY', 'Paraguay',now(), now());
INSERT INTO `countries` VALUES (null, 'PE', 'Peru',now(), now());
INSERT INTO `countries` VALUES (null, 'PH', 'Philippines',now(), now());
INSERT INTO `countries` VALUES (null, 'PN', 'Pitcairn',now(), now());
INSERT INTO `countries` VALUES (null, 'PL', 'Poland',now(), now());
INSERT INTO `countries` VALUES (null, 'PT', 'Portugal',now(), now());
INSERT INTO `countries` VALUES (null, 'PR', 'Puerto Rico',now(), now());
INSERT INTO `countries` VALUES (null, 'QA', 'Qatar',now(), now());
INSERT INTO `countries` VALUES (null, 'RE', 'Reunion',now(), now());
INSERT INTO `countries` VALUES (null, 'RO', 'Romania',now(), now());
INSERT INTO `countries` VALUES (null, 'RU', 'Russian Federation',now(), now());
INSERT INTO `countries` VALUES (null, 'RW', 'Rwanda',now(), now());
INSERT INTO `countries` VALUES (null, 'KN', 'Saint Kitts and Nevis',now(), now());
INSERT INTO `countries` VALUES (null, 'LC', 'Saint Lucia',now(), now());
INSERT INTO `countries` VALUES (null, 'VC', 'Saint Vincent and the Grenadines',now(), now());
INSERT INTO `countries` VALUES (null, 'WS', 'Samoa',now(), now());
INSERT INTO `countries` VALUES (null, 'SM', 'San Marino',now(), now());
INSERT INTO `countries` VALUES (null, 'ST', 'Sao Tome and Principe',now(), now());
INSERT INTO `countries` VALUES (null, 'SA', 'Saudi Arabia',now(), now());
INSERT INTO `countries` VALUES (null, 'SN', 'Senegal',now(), now());
INSERT INTO `countries` VALUES (null, 'RS', 'Serbia',now(), now());
INSERT INTO `countries` VALUES (null, 'SC', 'Seychelles',now(), now());
INSERT INTO `countries` VALUES (null, 'SL', 'Sierra Leone',now(), now());
INSERT INTO `countries` VALUES (null, 'SG', 'Singapore',now(), now());
INSERT INTO `countries` VALUES (null, 'SK', 'Slovakia',now(), now());
INSERT INTO `countries` VALUES (null, 'SI', 'Slovenia',now(), now());
INSERT INTO `countries` VALUES (null, 'SB', 'Solomon Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'SO', 'Somalia',now(), now());
INSERT INTO `countries` VALUES (null, 'ZA', 'South Africa',now(), now());
INSERT INTO `countries` VALUES (null, 'GS', 'South Georgia South Sandwich Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'ES', 'Spain',now(), now());
INSERT INTO `countries` VALUES (null, 'LK', 'Sri Lanka',now(), now());
INSERT INTO `countries` VALUES (null, 'SH', 'St. Helena',now(), now());
INSERT INTO `countries` VALUES (null, 'PM', 'St. Pierre and Miquelon',now(), now());
INSERT INTO `countries` VALUES (null, 'SD', 'Sudan',now(), now());
INSERT INTO `countries` VALUES (null, 'SR', 'Suriname',now(), now());
INSERT INTO `countries` VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'SZ', 'Swaziland',now(), now());
INSERT INTO `countries` VALUES (null, 'SE', 'Sweden',now(), now());
INSERT INTO `countries` VALUES (null, 'CH', 'Switzerland',now(), now());
INSERT INTO `countries` VALUES (null, 'SY', 'Syrian Arab Republic',now(), now());
INSERT INTO `countries` VALUES (null, 'TW', 'Taiwan',now(), now());
INSERT INTO `countries` VALUES (null, 'TJ', 'Tajikistan',now(), now());
INSERT INTO `countries` VALUES (null, 'TZ', 'Tanzania, United Republic of',now(), now());
INSERT INTO `countries` VALUES (null, 'TH', 'Thailand',now(), now());
INSERT INTO `countries` VALUES (null, 'TG', 'Togo',now(), now());
INSERT INTO `countries` VALUES (null, 'TK', 'Tokelau',now(), now());
INSERT INTO `countries` VALUES (null, 'TO', 'Tonga',now(), now());
INSERT INTO `countries` VALUES (null, 'TT', 'Trinidad and Tobago',now(), now());
INSERT INTO `countries` VALUES (null, 'TN', 'Tunisia',now(), now());
INSERT INTO `countries` VALUES (null, 'TR', 'Turkey',now(), now());
INSERT INTO `countries` VALUES (null, 'TM', 'Turkmenistan',now(), now());
INSERT INTO `countries` VALUES (null, 'TC', 'Turks and Caicos Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'TV', 'Tuvalu',now(), now());
INSERT INTO `countries` VALUES (null, 'UG', 'Uganda',now(), now());
INSERT INTO `countries` VALUES (null, 'UA', 'Ukraine',now(), now());
INSERT INTO `countries` VALUES (null, 'AE', 'United Arab Emirates',now(), now());
INSERT INTO `countries` VALUES (null, 'GB', 'United Kingdom',now(), now());
INSERT INTO `countries` VALUES (null, 'US', 'United States',now(), now());
INSERT INTO `countries` VALUES (null, 'UM', 'United States minor outlying islands',now(), now());
INSERT INTO `countries` VALUES (null, 'UY', 'Uruguay',now(), now());
INSERT INTO `countries` VALUES (null, 'UZ', 'Uzbekistan',now(), now());
INSERT INTO `countries` VALUES (null, 'VU', 'Vanuatu',now(), now());
INSERT INTO `countries` VALUES (null, 'VA', 'Vatican City State',now(), now());
INSERT INTO `countries` VALUES (null, 'VE', 'Venezuela',now(), now());
INSERT INTO `countries` VALUES (null, 'VN', 'Vietnam',now(), now());
INSERT INTO `countries` VALUES (null, 'VG', 'Virgin Islands (British)',now(), now());
INSERT INTO `countries` VALUES (null, 'VI', 'Virgin Islands (U.S.)',now(), now());
INSERT INTO `countries` VALUES (null, 'WF', 'Wallis and Futuna Islands',now(), now());
INSERT INTO `countries` VALUES (null, 'EH', 'Western Sahara',now(), now());
INSERT INTO `countries` VALUES (null, 'YE', 'Yemen',now(), now());
INSERT INTO `countries` VALUES (null, 'ZR', 'Zaire',now(), now());
INSERT INTO `countries` VALUES (null, 'ZM', 'Zambia',now(), now());
INSERT INTO `countries` VALUES (null, 'ZW', 'Zimbabwe',now(), now());